<?php require_once dirname(__FILE__).'/empluser-list.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-unitgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-unitform.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-deptgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-deptform.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-sitegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-siteform.phtml' ?>

